### ISSUE TITLE
Does not automatically protect from dubiousness

### ISSUE THREAD

**Issue by ckdake** [killpack/really#1]
Steps to reproduce:
1. put URL of dubious nature in browser (e.g. http://www.clickhole.com/)

Expected Result:
1. Profit

Actual Result:
1. Wait it is 4pm already?

**Comment by killpack** [comment]
Alas, this product cannot determine _a priori_ what is and what is not dubious.
Probably the way to go here is to develop a cloud-based neural network Big Data™ processing architecture platform plugin to determine dubiosity (or CBNNBDPAPP2DD) that we can just hook into.

**Comment by ckdake** [comment]
:moneybag:
